### ISSUE TITLE
Doesn't seem to have real-time updating?

### ISSUE THREAD

**Issue by garyrob** [WebReflection/viper-news#4]
I was very impressed with the load times for this HN clone, but it doesn't seem to show live updates, as for example, the Preact HN clone at https://preact-hn.appspot.com/ does. So, while the viperHTML version loads more quickly, the two clones don't really seem to have comparable functionality.

Is viper-news supposed to show live updates? Perhaps something is just broken at the moment?

**Comment by WebReflection** [comment]
It wasn't a requirement at that time but you can set a timer and refresh the render whenever you want.

This specific demo is more about 100% SSR chiming in later on with hyperHTML as companion on top.
It was created to show that the two work seamlessly together and can share same views.

HNPWA has no strict requirements, and all demoes have/do something slightly different.
