### ISSUE TITLE
Server side rendering

### ISSUE THREAD

**Issue by laszbalo** [WebReflection/viper-news#5]
Hello,

I was trying to run viper-news locally, but I am having an issue when I click user links ('/user/xzy') or item links (/item/abc). I got UnhandledPromiseRejectionWarning's and my request times out. It is happening because Firebase returns some sort of error messages instead of valid objects. Is there some settings for Firebase which you have not checked in, and I have to add manually?

With thanks,
Laszlo

P.S. I find viper/hiperHTML a great piece of engineering.

edit:

It works great when JS enabled on the client, but I am only interested in server side rendering at the moment.

**Comment by WebReflection** [comment]
when you use `model.style` in the index view but you pass `model.style` to the header one ... silly bugs like this happen :smile: 

sorry for that (fixed now, will deploy a more updated version soon)

**Comment by laszbalo** [comment]
No worries, just checked, now it is working as expected.
