### ISSUE TITLE
First load - error on HN pwa

### ISSUE THREAD

**Issue by sourcegr** [WebReflection/viper-news#6]
When clicking on the link provided https://viperhtml-164315.appspot.com/top/1

on first load, the links are beeing sanitized and displayed as plain text

![image](https://user-images.githubusercontent.com/3933935/34733625-ad23708c-f571-11e7-95b0-82f35ced081e.png)

**Comment by WebReflection** [comment]
I forgot to deploy latest ... it should be fine now, thanks.
