### ISSUE TITLE
HTML "about" content rendered as plain text

### ISSUE THREAD

**Issue by r0mflip** [WebReflection/viper-news#9]
This happens when I visit [https://viperhtml-164315.appspot.com/user/DoreenMichele](https://viperhtml-164315.appspot.com/user/DoreenMichele)

![HTML about content being rendered as plain text](https://user-images.githubusercontent.com/37770235/39322090-5be313b0-49a6-11e8-9cee-a00f1fb25239.png)

**Comment by WebReflection** [comment]
Fixed, thanks.
